# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bytesize
email: webmaster@bytesize.dev
description: >
  An evergreen and ever growing collection of web development concepts and code examples
  geared towards software engineers that are either new or looking to simplify.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bytesize.dev" # the base hostname & protocol for your site
github_url: "https://raw.githubusercontent.com/tylerchilds/bytesize/master"

cache_buster: 20190405_1

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
